---
apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Kibana
metadata:
  name: kibana
spec:
  replicas: 1
  esCluster:
    host: http://elasticsearch-master:9200
    esVersion: 7.16.0
    clusterName: elasticsearch
  kubernetesConfig:
    nodeSelectors:
      kubernetes.io/os: linux
  esSecurity:
    tlsEnabled: true
    existingSecret: elasticsearch-password
