# permissions for end users to edit fluentds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-editor-role
rules:
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - fluentds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - fluentds/status
  verbs:
  - get
