# permissions for end users to view kibanas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kibana-viewer-role
rules:
- apiGroups:
  - logging.logging.opstreelabs.in
  resources:
  - kibanas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.logging.opstreelabs.in
  resources:
  - kibanas/status
  verbs:
  - get
