---
apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Fluentd
metadata:
  name: fluentd
spec:
  esCluster:
    host: elasticsearch-master
  kubernetesConfig:
    nodeSelectors:
      kubernetes.io/os: linux
  esSecurity:
    tlsEnabled: true
    existingSecret: elasticsearch-password
  indexNameStrategy: namespace_name
