---
apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Fluentd
metadata:
  name: fluentd
spec:
  esCluster:
    host: elasticsearch-master
  kubernetesConfig:
    elasticAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: beta.kubernetes.io/os
                  operator: In
                  values:
                    - linux
  esSecurity:
    tlsEnabled: true
    existingSecret: elasticsearch-password
  indexNameStrategy: namespace_name
