---
apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Kibana
metadata:
  name: kibana
spec:
  replicas: 1
  esCluster:
    host: https://elasticsearch-master:9200
    esVersion: 7.16.0
    clusterName: elasticsearch
  kubernetesConfig:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 2000m
        memory: 2Gi
  esSecurity:
    tlsEnabled: true
    existingSecret: elasticsearch-password
