---
apiVersion: logging.opstreelabs.in/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-cluster
  labels:
    organization: opstree
    owned-by: Abhishek
  namespace: logging-operator
spec:
  clusterName: "production"
  image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
  imagePullPolicy: "IfNotPresent"
  security:
    tlsEnabled: true
    password: "Opstree@1234"
  plugins: ["repository-s3"]
  master:
    enabled: true
    count: 3
    # extraEnvVariables:
    #   foo: bar
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        cpu: 500m
        memory: 2048Mi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
        selector: {}
    jvmOptions:
      Xmx: "1g"
      Xms: "1g"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - "elasticsearch-cluster-master"
          topologyKey: kubernetes.io/hostname
  data:
    enabled: true
    count: 2
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        cpu: 500m
        memory: 2048Mi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
        selector: {}
    jvmOptions:
      Xmx: "1g"
      Xms: "1g"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - "elasticsearch-cluster-data"
          topologyKey: kubernetes.io/hostname
  ingestion:
    enabled: true
    count: 1
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        cpu: 500m
        memory: 2048Mi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
        selector: {}
    jvmOptions:
      Xmx: "1g"
      Xms: "1g"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - "elasticsearch-cluster-ingestion"
          topologyKey: kubernetes.io/hostname
  client:
    enabled: true
    count: 1
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        cpu: 500m
        memory: 2048Mi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
        selector: {}
    jvmOptions:
      Xmx: "1g"
      Xms: "1g"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - "elasticsearch-cluster-ingestion"
          topologyKey: kubernetes.io/hostname
