---
apiVersion: logging.opstreelabs.in/v1alpha1
kind: IndexLifecycle
metadata:
  name: indexlifecycle-example
spec:
  enabled: true
  rollover:
    maxSize: 2GB
    maxAge: 30d
  delete:
    minAge: 15d
  elasticsearch:
    host: "https://elasticsearch-cluster-ingestion:9200"
    username: elastic
    password: "Opstree@1234"
