---
apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Fluentd
metadata:
  name: fluentd
spec:
  esCluster:
    host: elasticsearch-master
  kubernetesConfig:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 2000m
        memory: 2Gi
  esSecurity:
    tlsEnabled: true
    existingSecret: elasticsearch-password
  indexNameStrategy: namespace_name
