{{- if .Values.lifecycle.enabled }}
{{- range .Values.lifecycle.policies }}
---
apiVersion: logging.opstreelabs.in/v1alpha1
kind: IndexLifecycle
metadata:
  name: {{ .name }}
spec:
  enabled: {{ .status }}
  rollover:
    maxSize: {{ .maxSize }}
    maxAge: {{ .maxAge }}
  delete:
    minAge: {{ .deletionAge }}
  elasticsearch:
    host: {{ $.Values.lifecycle.elasticsearch.host }}
    username: {{ $.Values.lifecycle.elasticsearch.username }}
    password: {{ $.Values.lifecycle.elasticsearch.password }}
{{- end }}
{{- end }}
