---
apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  esClusterName: "prod"
  esVersion: "7.17.0"
  esSecurity:
    autoGeneratePassword: true
    tlsEnabled: true
