---
apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Fluentd
metadata:
  name: fluentd
spec:
  esCluster:
    host: elasticsearch-master
  kubernetesConfig:
    tolerations:
      - key: "example-key"
        operator: "Exists"
        effect: "NoSchedule"
  esSecurity:
    tlsEnabled: true
    existingSecret: elasticsearch-password
  indexNameStrategy: namespace_name
