---
apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  esClusterName: "prod"
  esVersion: "7.16.0"
  esMaster:
    replicas: 4
    storage:
      storageSize: 2Gi
      accessModes: [ReadWriteOnce]
      storageClass: do-block-storage
    jvmMaxMemory: "1g"
    jvmMinMemory: "1g"
  esSecurity:
    autoGeneratePassword: true
    tlsEnabled: true
